#ifndef TUNING_TUNING_METADATA_HPP
#define TUNING_TUNING_METADATA_HPP

#include "tuning/tuning_types.hpp"

#include <array>
#include <string_view>

namespace Tuning {

enum class TuningFieldId {
    EvaluationBishopBadHeavyPenalty,
    EvaluationBishopBadLightPenalty,
    EvaluationBishopPairEg,
    EvaluationBishopPairMg,
    EvaluationEndgameLatePhaseMax,
    EvaluationEndgameMopUpEgMargin,
    EvaluationEndgameMopUpMaterialMargin,
    EvaluationEndgameMopUpWeights,
    EvaluationEndgameScaleMinorOnlyClearEdge,
    EvaluationEndgameScaleMinorOnlyNearEqual,
    EvaluationEndgameScaleOppositeBishopsLowPawns,
    EvaluationEndgameScaleOppositeBishopsMinPawns,
    EvaluationKingAttackPressure,
    EvaluationKingShieldMaxPawns,
    EvaluationKingShieldPerPawnBonus,
    EvaluationKingUncastledCenterPenalty,
    EvaluationKingUncastledLostRightsPenalty,
    EvaluationMaterialEg,
    EvaluationMaterialMg,
    EvaluationMobilityEg,
    EvaluationMobilityMg,
    EvaluationPawnsBackwardByRankEg,
    EvaluationPawnsBackwardByRankMg,
    EvaluationPawnsCandidateByRankEg,
    EvaluationPawnsCandidateByRankMg,
    EvaluationPawnsConnectedByRankEg,
    EvaluationPawnsConnectedByRankMg,
    EvaluationPawnsDoubledPenalty,
    EvaluationPawnsIslandPenaltyEg,
    EvaluationPawnsIslandPenaltyMg,
    EvaluationPawnsIsolatedPenalty,
    EvaluationPawnsPassedBlockedDivisor,
    EvaluationPawnsPassedCountBonusEg,
    EvaluationPawnsPassedCountBonusMg,
    EvaluationPawnsPassedEgMultiplier,
    EvaluationPawnsPassedRankSquareMultiplier,
    EvaluationPhaseIncrements,
    EvaluationPstEgPesto,
    EvaluationPstMgPesto,
    EvaluationQueenEarlyUndevelopedMinorPenalty,
    EvaluationRookTrappedPenalty,
    EvaluationRookActivityEg,
    EvaluationRookActivityMg,
    EvaluationTaperScale,
    OpeningBookDepth,
    OpeningEnabled,
    OpeningSeed,
    OpeningSelectionMode,
    OpeningSelectionTopN,
    SearchAspirationWindowCp,
    SearchFutilityForwardMarginPerDepthCp,
    SearchFutilityReverseMarginPerDepthCp,
    SearchHistoryCap,
    SearchLmrBase,
    SearchNullMoveReduction,
    SearchOrderingCaptureScores,
    SearchOrderingMvvLva,
    SearchOrderingPromotionBase,
    SearchOrderingQuietScores,
    SearchOrderingTtMoveScore,
    SearchQuiescenceDeltaPruningMarginCp,
    SearchSeePieceValues,
    SearchSingularMarginCp,
    TimeCriticalLowTimeReserveMs,
    TimeCriticalLowTimeThresholdMs,
    TimeExpectedMovesBase,
    TimeExpectedMovesFloor,
    TimeHardStopFraction,
    TimeInstabilityMultiplier,
    TimeInstabilityThresholdCp,
    TimeMaxClockFraction,
    TimeMinimumMoveTimeMs,
    TimePollingNodeMask,
    TimeSafetyReserveMs,
    TimeSoftStopStablePercent,
    TimeSoftStopUnstablePercent,
    Count,
};

struct TuningFieldMetadata {
    TuningFieldId id;
    std::string_view stableName;
    TuningCategory category;
    TuningValueType valueType;
    std::string_view unit;
    BoundsStatus boundsStatus;
    MappingEquivalence equivalence;
};

inline constexpr std::array<TuningFieldMetadata, static_cast<std::size_t>(TuningFieldId::Count)> TUNING_FIELDS = {{
    {TuningFieldId::EvaluationBishopBadHeavyPenalty, "evaluation.bishop.badHeavyPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationBishopBadLightPenalty, "evaluation.bishop.badLightPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationBishopPairEg, "evaluation.bishopPair.eg", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationBishopPairMg, "evaluation.bishopPair.mg", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameLatePhaseMax, "evaluation.endgame.latePhaseMax", TuningCategory::EvaluationPhase, TuningValueType::Integer, "phase unit", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameMopUpEgMargin, "evaluation.endgame.mopUpEgMargin", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameMopUpMaterialMargin, "evaluation.endgame.mopUpMaterialMargin", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameMopUpWeights, "evaluation.endgame.mopUpWeights", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn formula weights", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameScaleMinorOnlyClearEdge, "evaluation.endgame.scaleMinorOnlyClearEdge", TuningCategory::EvaluationScalar, TuningValueType::Integer, "scaled score numerator", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameScaleMinorOnlyNearEqual, "evaluation.endgame.scaleMinorOnlyNearEqual", TuningCategory::EvaluationScalar, TuningValueType::Integer, "scaled score numerator", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameScaleOppositeBishopsLowPawns, "evaluation.endgame.scaleOppositeBishopsLowPawns", TuningCategory::EvaluationScalar, TuningValueType::Integer, "scaled score numerator", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationEndgameScaleOppositeBishopsMinPawns, "evaluation.endgame.scaleOppositeBishopsMinPawns", TuningCategory::EvaluationScalar, TuningValueType::Integer, "scaled score numerator", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationKingAttackPressure, "evaluation.king.attackPressure", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn penalty by attacker count", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationKingShieldMaxPawns, "evaluation.king.shieldMaxPawns", TuningCategory::EvaluationScalar, TuningValueType::Integer, "pawn count cap", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationKingShieldPerPawnBonus, "evaluation.king.shieldPerPawnBonus", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn per pawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationKingUncastledCenterPenalty, "evaluation.king.uncastledCenterPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationKingUncastledLostRightsPenalty, "evaluation.king.uncastledLostRightsPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationMaterialEg, "evaluation.material.eg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationMaterialMg, "evaluation.material.mg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationMobilityEg, "evaluation.mobility.eg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn per legal destination", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationMobilityMg, "evaluation.mobility.mg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn per legal destination", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsBackwardByRankEg, "evaluation.pawns.backwardByRank.eg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn penalty by relative rank", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsBackwardByRankMg, "evaluation.pawns.backwardByRank.mg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn penalty by relative rank", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsCandidateByRankEg, "evaluation.pawns.candidateByRank.eg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn by relative rank", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsCandidateByRankMg, "evaluation.pawns.candidateByRank.mg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn by relative rank", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsConnectedByRankEg, "evaluation.pawns.connectedByRank.eg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn by relative rank", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsConnectedByRankMg, "evaluation.pawns.connectedByRank.mg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn by relative rank", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsDoubledPenalty, "evaluation.pawns.doubledPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsIslandPenaltyEg, "evaluation.pawns.islandPenalty.eg", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn per extra pawn island", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsIslandPenaltyMg, "evaluation.pawns.islandPenalty.mg", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn per extra pawn island", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsIsolatedPenalty, "evaluation.pawns.isolatedPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsPassedBlockedDivisor, "evaluation.pawns.passedBlockedDivisor", TuningCategory::EvaluationScalar, TuningValueType::Integer, "divisor", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsPassedCountBonusEg, "evaluation.pawns.passedCountBonus.eg", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn per passed pawn count difference", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsPassedCountBonusMg, "evaluation.pawns.passedCountBonus.mg", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn per passed pawn count difference", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsPassedEgMultiplier, "evaluation.pawns.passedEgMultiplier", TuningCategory::EvaluationScalar, TuningValueType::Integer, "multiplier", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPawnsPassedRankSquareMultiplier, "evaluation.pawns.passedRankSquareMultiplier", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn multiplier by relative-rank squared", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPhaseIncrements, "evaluation.phase.increments", TuningCategory::EvaluationPhase, TuningValueType::IntegerArray, "phase unit", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationPstEgPesto, "evaluation.pst.egPesto", TuningCategory::EvaluationPieceSquareTable, TuningValueType::IntegerArray, "centipawn by piece and square", BoundsStatus::Unknown, MappingEquivalence::StructurallyRepresentedOnly},
    {TuningFieldId::EvaluationPstMgPesto, "evaluation.pst.mgPesto", TuningCategory::EvaluationPieceSquareTable, TuningValueType::IntegerArray, "centipawn by piece and square", BoundsStatus::Unknown, MappingEquivalence::StructurallyRepresentedOnly},
    {TuningFieldId::EvaluationQueenEarlyUndevelopedMinorPenalty, "evaluation.queen.earlyUndevelopedMinorPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty per extra undeveloped minor", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationRookTrappedPenalty, "evaluation.rook.trappedPenalty", TuningCategory::EvaluationScalar, TuningValueType::Integer, "centipawn penalty", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationRookActivityEg, "evaluation.rookActivity.eg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationRookActivityMg, "evaluation.rookActivity.mg", TuningCategory::EvaluationArray, TuningValueType::IntegerArray, "centipawn", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::EvaluationTaperScale, "evaluation.taper.scale", TuningCategory::EvaluationPhase, TuningValueType::Integer, "scale denominator", BoundsStatus::Provisional, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::OpeningBookDepth, "opening.bookDepth", TuningCategory::OpeningSelection, TuningValueType::Integer, "plies in SAN history", BoundsStatus::Verified, MappingEquivalence::RuntimeTestEquivalence},
    {TuningFieldId::OpeningEnabled, "opening.enabled", TuningCategory::OpeningSelection, TuningValueType::Boolean, "uci option", BoundsStatus::Verified, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::OpeningSeed, "opening.seed", TuningCategory::OpeningRandomness, TuningValueType::UnsignedInteger, "uint32 seed", BoundsStatus::Verified, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::OpeningSelectionMode, "opening.selectionMode", TuningCategory::OpeningSelection, TuningValueType::Enum, "uci combo", BoundsStatus::Verified, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::OpeningSelectionTopN, "opening.selectionTopN", TuningCategory::OpeningSelection, TuningValueType::Integer, "candidate count", BoundsStatus::Verified, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchAspirationWindowCp, "search.aspiration.windowCp", TuningCategory::SearchPruning, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchFutilityForwardMarginPerDepthCp, "search.futility.forwardMarginPerDepthCp", TuningCategory::SearchPruning, TuningValueType::Integer, "centipawn per depth", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchFutilityReverseMarginPerDepthCp, "search.futility.reverseMarginPerDepthCp", TuningCategory::SearchPruning, TuningValueType::Integer, "centipawn per depth", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchHistoryCap, "search.history.cap", TuningCategory::SearchMoveOrdering, TuningValueType::Integer, "history score absolute cap", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchLmrBase, "search.lmr.baseScaled100", TuningCategory::SearchReduction, TuningValueType::ScaledInteger, "base * 100", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchNullMoveReduction, "search.nullMove.reduction", TuningCategory::SearchReduction, TuningValueType::Integer, "ply", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchOrderingCaptureScores, "search.ordering.captureScores", TuningCategory::SearchMoveOrdering, TuningValueType::IntegerArray, "relative move-ordering score", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchOrderingMvvLva, "search.ordering.mvvLva", TuningCategory::SearchMoveOrdering, TuningValueType::IntegerArray, "relative move-ordering score", BoundsStatus::Unknown, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchOrderingPromotionBase, "search.ordering.promotionBase", TuningCategory::SearchMoveOrdering, TuningValueType::Integer, "relative move-ordering score", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchOrderingQuietScores, "search.ordering.quietScores", TuningCategory::SearchMoveOrdering, TuningValueType::IntegerArray, "relative move-ordering score", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchOrderingTtMoveScore, "search.ordering.ttMoveScore", TuningCategory::SearchMoveOrdering, TuningValueType::Integer, "relative move-ordering score", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchQuiescenceDeltaPruningMarginCp, "search.quiescence.deltaPruningMarginCp", TuningCategory::SearchQuiescence, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchSeePieceValues, "search.see.pieceValues", TuningCategory::SearchMoveOrdering, TuningValueType::IntegerArray, "centipawn exchange value", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::SearchSingularMarginCp, "search.singular.marginCp", TuningCategory::SearchExtension, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeCriticalLowTimeReserveMs, "time.criticalLowTimeReserveMs", TuningCategory::TimeDeadline, TuningValueType::Integer, "millisecond", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeCriticalLowTimeThresholdMs, "time.criticalLowTimeThresholdMs", TuningCategory::TimeDeadline, TuningValueType::Integer, "millisecond", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeExpectedMovesBase, "time.expectedMovesBase", TuningCategory::TimeAllocation, TuningValueType::Integer, "moves", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeExpectedMovesFloor, "time.expectedMovesFloor", TuningCategory::TimeAllocation, TuningValueType::Integer, "moves", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeHardStopFraction, "time.hardStopFraction", TuningCategory::TimeDeadline, TuningValueType::IntegerArray, "fraction numerator denominator", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeInstabilityMultiplier, "time.instabilityMultiplierPermille", TuningCategory::TimeAllocation, TuningValueType::ScaledInteger, "multiplier * 1000", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeInstabilityThresholdCp, "time.instabilityThresholdCp", TuningCategory::TimeAllocation, TuningValueType::Integer, "centipawn", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeMaxClockFraction, "time.maxClockFractionDenominator", TuningCategory::TimeAllocation, TuningValueType::Integer, "denominator", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeMinimumMoveTimeMs, "time.minimumMoveTimeMs", TuningCategory::TimeAllocation, TuningValueType::Integer, "millisecond", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimePollingNodeMask, "time.polling.nodeMask", TuningCategory::TimePolling, TuningValueType::UnsignedInteger, "bitmask", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeSafetyReserveMs, "time.safetyReserveMs", TuningCategory::TimeAllocation, TuningValueType::Integer, "millisecond", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeSoftStopStablePercent, "time.softStop.stablePercent", TuningCategory::TimeDeadline, TuningValueType::Integer, "percent", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
    {TuningFieldId::TimeSoftStopUnstablePercent, "time.softStop.unstablePercent", TuningCategory::TimeDeadline, TuningValueType::Integer, "percent", BoundsStatus::Provisional, MappingEquivalence::CompileTimeEquivalence},
}};

static_assert(TUNING_FIELDS.size() == 76);

[[nodiscard]] constexpr const TuningFieldMetadata& metadataFor(TuningFieldId id) noexcept {
    return TUNING_FIELDS[static_cast<std::size_t>(id)];
}

} // namespace Tuning

#endif
